---
- name: update homebrew
  homebrew:
    update_homebrew: yes

- name: upgrade homebrew packages
  command: brew upgrade

- name: install homebrew packages
  homebrew:
    name: "{{ brew_packages }}"
    state: present
