---
- name: install erlang plugin for asdf
  command: asdf plugin add erlang
  ignore_errors: true

- name: install elixir plugin for asdf
  command: asdf plugin add elixir
  ignore_errors: true

- name: install erlang
  command: asdf install erlang {{ item }}
  with_items: "{{ erlang_versions }}"
  notify: update default erlang

- name: install elixir
  command: asdf install elixir {{ item }}
  with_items: "{{ elixir_versions }}"
  notify: update default elixir
