---
- name: install nodejs plugin for asdf
  command: ~/.asdf/bin/asdf plugin add nodejs
  ignore_errors: true

- name: install nodejs
  command: ~/.asdf/bin/asdf install nodejs {{ item }}
  with_items: "{{ nodejs_versions }}"
  notify: update default nodejs

- name: install yarn
  homebrew:
    name: yarn
    state: present
  notify: update nodejs shims


- name: install yarn packages
  yarn:
    name: "{{ item }}"
    state: present
    global: true
  with_items: "{{ yarn_packages }}"
  notify: update nodejs shims
