---
- name: install python plugin for asdf
  command: asdf plugin add python
  ignore_errors: true

- name: install python
  command: asdf install python {{ item }}
  with_items: "{{ python_versions }}"
  notify:
    - update python shims

- meta: flush_handlers

- name: install python packages
  pip:
    name: "{{ item }}"
    state: present
    executable: ~/.asdf/installs/python/{{ default_python_version }}/bin/pip
    chdir: ~/.asdf/installs/python/{{ default_python_version }}/bin/python
  with_items: "{{ pip_packages }}"
  notify: update python shims
