---
# custom/nodejs

- name: update default nodejs
  command: asdf global nodejs {{ default_nodejs_version }}

- name: update nodejs shims
  command: asdf reshim nodejs

# custom/python

- name: update default python
  command: asdf global python {{ default_python_version }}

- name: update python shims
  command: asdf reshim python

# custom/ruby

- name: update default ruby
  command: asdf global ruby {{ default_ruby_version }}

- name: update ruby shims
  command: asdf reshim ruby

# custom/elixir

- name: update default erlang
  command: asdf global erlang {{ default_erlang_version }}

- name: update erlang shims
  command: asdf reshim erlang

- name: update default elixir
  command: asdf global elixir {{ default_elixir_version }}

- name: update elixir shims
  command: asdf reshim elixir
