---
brew_taps:
  - homebrew/cask
  - homebrew/core
  - homebrew/cask-fonts
  - datawire/blackbird

brew_packages:
  - autojump
  - awscli
  - ctags
  - fish
  - fswatch
  - fzf
  - htop
  - mas
  - minikube
  - neovim
  - postgresql
  - the_silver_searcher
  - tree

cask_packages:
  - 1password
  - alacritty
  - alfred
  - brave-browser
  - dash
  - discord
  - drawio
  - figma
  - firefox
  - font-jetbrains-mono
  - google-drive
  - google-chrome
  - iterm2
  - mockoon
  - numi
  - oracle-jdk
  - postman
  - slack
  - spotify
  - telegram
  - visual-studio-code
  - whatsapp

mas_packages:
  - 1091189122  # Bear
  - 441258766   # Magnet
  - 539883307   # LINE

# custom/zsh

zsh_packages:
  - zsh-autosuggestions
  - zsh-syntax-highlighting

# custom/nodejs

nodejs_versions:
  - 18.9.0

default_nodejs_version: 18.9.0

yarn_packages:
  - neovim
  - pm2
  - dockly

# custom/python

python_versions:
  - 3.11.0

default_python_version: 3.11.0

pip_packages:
  - pip
  - virtualenv
  - pipenv
  - autopep8
  - pynvim

# custom/ruby

ruby_versions:
  - 3.1.1

default_ruby_version: 3.1.1

gem_packages:
  - neovim
  - bundler
  - rails
  - pry

# custom/elixir

erlang_versions:
  - 24.0.2
  - 24.1.7

elixir_versions:
  - 1.13.2

default_erlang_version: 24.1.7
default_elixir_version: 1.13.2

# custom/kubernetes

kubernetes_packages:
  - kubernetes-cli
  - kubernetes-helm
  - kubectx
